{% set name = "django-select2" %}
{% set version = "8.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9975a74f13f20468d07deae027672045f58e0d6d1983c305805ba40b16a0f0ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - flit >=3.2
    - flit-scm
    - wheel
    - django >=3.2
    - django-appconf >=0.6.0
  run:
    - python >={{ python_min }}
    - django >=3.2
    - django-appconf >=0.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - django_select2

about:
  home: https://pypi.org/project/django-select2/
  summary: django-select2, select2 driven Django Widgets.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/codingjoe/django-select2
  doc_url: https://django-select2.readthedocs.io/

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
