{% set name = "django-select2" %}
{% set version = "8.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1de547c89ee2f005f1d461f76db89b440897939fcea894db8ba756b6f1ad36c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}.*
    - setuptools
    - setuptools_scm
    - flit >=3.2
    - flit-scm
    - wheel
    - django >=3.2
    - django-appconf >=0.6.0
  run:
    - python >={{ python_min }}
    - __unix  # [unix]
    - __win   # [win]
    - django >=3.2
    - django-appconf >=0.6.0

test:
  imports:
    - django_select2

about:
  home: https://pypi.org/project/django-select2/
  summary: django-select2, select2 driven Django Widgets.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/codingjoe/django-select2
  doc_url: https://django-select2.readthedocs.io/

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
